FROM fedora:42

RUN dnf -y --setopt=install_weak_deps=False install \
    @development-tools \
    cmake \
    ninja-build \
    pkgconf \
    qt6-qtbase-devel \
    qt6-qttools-devel \
    qt6-qtwayland-devel \
    wayland-protocols-devel \
    libxkbcommon-devel \
    gtest-devel \
  && dnf -y clean all && rm -rf /var/cache/dnf

WORKDIR /workspace
