FROM debian:trixie

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    pkgconf \
    qt6-base-dev \
    qt6-tools-dev \
    qt6-wayland-dev \
    wayland-protocols \
    qtchooser \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
